field_default:
    serie_rps: "EN001"
    status_rps: 1

field_validate:
    num_field: 47
    fields:
        1:
            name: "Identificação Venda"
            required: false
            method: "setIdentificacaoVenda"
            regex: "/^.*$/"
            limit: 50
            default: null
        2:
            name: "Tipo do RPS"
            required: true
            method: "setTipoRps"
            regex: "/^[0-1]{1}$/"
            limit: 1
            default: 0
        3:
            name: "Data de Emissão do RPS"
            required: true
            method: "setDataEmissao"
            regex: "/^[0-9]{4}\\-[0-9]{2}\\-[0-9]{2}$/"
            limit: 10
            default: null
            convert: "DateTime::createFromFormat('Y-m-d', '$value')"
        4:
            name: "Identificação de CPF ou CNPJ do Tomador de Serviços"
            required: true
            method: "setTipoIdentificaoTomador"
            regex: "/^[1-3]{1}$/"
            limit: 1
            default: null
        5:
            name: "CPF ou CNPJ do Tomador de Serviços"
            required: true
            method: "setIdentificacaoTomador"
            regex: "/^[0-9]{11,14}$/"
            limit: 14
            default: null
        6:
            name: "Inscrição Municipal do Tomador"
            required: false
            method: "setInscricaoMunicipalTomador"
            regex: "/^.{1,15}$/"
            limit: 15
            default: null
        7:
            name: "Inscrição Estadual do Tomador"
            required: false
            method: "setInscricaoEstadualTomador"
            regex: "/^.{1,15}$/"
            limit: 15
            default: null
        8:
            name: "Nome/Razão Social do Tomador"
            required: false
            method: "setNomeTomador"
            regex: "/^.{1,115}$/"
            limit: 115
            default: null
        9:
            name: "Tipo do Endereço do Tomador (Rua, Av, ...)"
            required: false
            method: "setTipoEnderecoTomador"
            regex: "/^.{1,3}$/"
            limit: 3
            default: null
        10:
            name: "Endereço do Tomador"
            required: false
            method: "setEnderecoTomador"
            regex: "/^.{1,125}$/"
            limit: 125
            default: null
        11:
            name: "Número do Endereço do Tomador"
            required: false
            method: "setNumeroEnderecoTomador"
            regex: "/^.{1,10}$/"
            limit: 10
            default: null
        12:
            name: "Complemento do Endereço do Tomador"
            required: false
            method: "setComplementoEnderecoTomador"
            regex: "/^.{1,60}$/"
            limit: 60
            default: null
        13:
            name: "Bairro do Tomador"
            required: false
            method: "setBairroTomador"
            regex: "/^.{1,72}$/"
            limit: 72
            default: null
        14:
            name: "Cidade do Tomador"
            required: false
            method: "setCidadeTomador"
            regex: "/^.{1,50}$/"
            limit: 50
            default: null
        15:
            name: "UF do Tomador"
            required: false
            method: "setUfTomador"
            regex: "/^[a-zA-Z]{1,2}$/"
            limit: 2
            default: null
            convert: "strtoupper('$value')"
        16:
            name: "CEP do Tomador"
            required: false
            method: "setCepTomador"
            regex: "/^[0-9]{7,8}$/"
            limit: 8
            default: null
        17:
            name: "Telefone de Contato do Tomador"
            required: false
            method: "setTelefoneTomador"
            regex: "/^.{1,11}$/"
            limit: 11
            default: null
        18:
            name: "E-mail do Tomador"
            required: false
            method: "setEmailTomador"
            regex: "/^.{1,80}$/"
            limit: 80
            default: null
        19:
            name: "Tipo de Tributação de Serviços"
            required: true
            method: "setTipoTributacaoServico"
            regex: "/^[1,6]{1}$/"
            limit: 1
            default: 1
        20:
            name: "Cidade de Prestação do Serviço"
            required: true
            method: "setCidadePrestacaoServico"
            regex: "/^.{1,50}$/"
            limit: 50
            default: "Rio de Janeiro"
        21:
            name: "UF de Prestação do Serviço"
            required: true
            method: "setUfPrestacaoServico"
            regex: "/^[a-zA-Z]{1,2}$/"
            limit: 2
            default: "RJ"
            convert: "strtoupper('$value')"
        22:
            name: "Regime Especial de Tributação"
            required: true
            method: "setRegimeEspecialTributacao"
            regex: "/^[0-6]{1}$/"
            limit: 1
            default: 0
        23:
            name: "Opção Pelo Simples"
            required: true
            method: "setOpcaoPeloSimples"
            regex: "/^[0-1]{1}$/"
            limit: 1
            default: 0
        24:
            name: "Incentivo Cultural"
            required: true
            method: "setIncentivoCultural"
            regex: "/^[0-1]{1}$/"
            limit: 1
            default: 0
        25:
            name: "Código do Serviço Federal"
            required: true
            method: "setCodigoServicoFederal"
            regex: "/^.{1,4}$/"
            limit: 4
            default: 802
        26:
            name: "Código do País"
            required: false
            method: "setCodigoPais"
            regex: "/^[0-9]{1,5}$/"
            limit: 5
            default: null
        27:
            name: "Código do Benefício"
            required: false
            method: "setCodigoBeneficio"
            regex: "/^[0-9]{1,3}$/"
            limit: 3
            default: null
        28:
            name: "Código do Serviço Municipal"
            required: true
            method: "setCodigoServicoMunicipal"
            regex: "/^.{1,6}$/"
            limit: 6
            default: 80216
        29:
            name: "Alíquota"
            required: true
            method: "setAliquota"
            regex: "/^[0-9]{1,5}$/"
            limit: 5
            default: 500
        30:
            name: "Valor dos Serviços"
            required: true
            method: "setValorServicos"
            regex: "/^[0-9]{1,15}$/"
            limit: 15
            default: null
        31:
            name: "Valor das Deduções"
            required: false
            method: "setValorDeducoes"
            regex: "/^[0-9]{1,15}$/"
            limit: 15
            default: null
        32:
            name: "Valor do Desconto Condicionado"
            required: false
            method: "setValorDescontoCondicionado"
            regex: "/^[0-9]{1,15}$/"
            limit: 15
            default: null
        33:
            name: "Valor do Desconto Incondicionado"
            required: false
            method: "setValorDescontoIncondicionado"
            regex: "/^[0-9]{1,15}$/"
            limit: 15
            default: null
        34:
            name: "Valor COFINS"
            required: false
            method: "setValorCofins"
            regex: "/^[0-9]{1,15}$/"
            limit: 15
            default: null
        35:
            name: "Valor CSLL"
            required: false
            method: "setValorCsll"
            regex: "/^[0-9]{1,15}$/"
            limit: 15
            default: null
        36:
            name: "Valor INSS"
            required: false
            method: "setValorIss"
            regex: "/^[0-9]{1,15}$/"
            limit: 15
            default: null
        37:
            name: "Valor IRPJ"
            required: false
            method: "setValorIrpj"
            regex: "/^[0-9]{1,15}$/"
            limit: 15
            default: null
        38:
            name: "Valor PIS/PASEP"
            required: false
            method: "setValorPisPasep"
            regex: "/^[0-9]{1,15}$/"
            limit: 15
            default: null
        39:
            name: "Valor de Outras Retenções Federais"
            required: false
            method: "setValorOutrasRetencoesFederais"
            regex: "/^[0-9]{1,15}$/"
            limit: 15
            default: null
        40:
            name: "Valor do ISS"
            required: false
            method: "setValorIss"
            regex: "/^[0-9]{1,15}$/"
            limit: 15
            default: null
        41:
            name: "ISS Retido"
            required: true
            method: "setIssRetido"
            regex: "/^[0-1]{1}$/"
            limit: 1
            default: 0
        42:
            name: "Data de Competência"
            required: true
            method: "setDataCompetencia"
            regex: "/^[0-9]{4}\\-[0-9]{2}\\-[0-9]{2}$/"
            limit: 10
            default: null
            convert: "DateTime::createFromFormat('Y-m-d', '$value')"
        43:
            name: "Código da Obra"
            required: false
            method: "setCodigoObra"
            regex: "/^.{1,15}$/"
            limit: 15
            default: null
        44:
            name: "Anotação de Responsabilidade Técnica"
            required: false
            method: "setAnotacaoResponsabilidadeTecnica"
            regex: "/^.{1,15}$/"
            limit: 15
            default: null
        45:
            name: "Série do RPS Substituido"
            required: false
            method: "setSerieRpsSubstituido"
            regex: "/^.{1,5}$/"
            limit: 5
            default: null
        46:
            name: "Número do RPS Substituido"
            required: false
            method: "setNumeroRpsSusbtituido"
            regex: "/^[0-9]{1,15}$/"
            limit: 15
            default: null
        47:
            name: "Discriminação dos Serviços"
            required: true
            method: "setDiscriminacaoServico"
            regex: "/^.+$/"
            limit: 4000
            default: null
            